[0m16:43:12.295485 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118927770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118946f00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118947b90>]}
[0m16:43:12.299354 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 16:43:12.299620 | 70b3c2c6-8fd9-4fa3-81da-c626eae8c910 ==============================
[0m16:43:12.299620 [info ] [MainThread]: Running with dbt=1.9.1
[0m16:43:12.299904 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/dallin/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt ', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:43:12.300518 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt_project.yml does not parse to a dictionary
[0m16:43:12.307797 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.059449833, "process_in_blocks": "0", "process_kernel_time": 0.115982, "process_mem_max_rss": "109068288", "process_out_blocks": "0", "process_user_time": 0.735308}
[0m16:43:12.308245 [debug] [MainThread]: Command `cli deps` failed at 16:43:12.308182 after 0.06 seconds
[0m16:43:12.308493 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100796ff0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1187fb320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1189471d0>]}
[0m16:43:12.308659 [debug] [MainThread]: An error was encountered while trying to send an event
[0m16:43:12.308794 [debug] [MainThread]: Flushing usage events
[0m16:51:16.058543 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112e66a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1131278c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1131471d0>]}
[0m16:51:16.062068 [debug] [MainThread]: An error was encountered while trying to send an event


============================== 16:51:16.062308 | 8665ca62-25ab-439c-b703-12898d07be6d ==============================
[0m16:51:16.062308 [info ] [MainThread]: Running with dbt=1.9.1
[0m16:51:16.062585 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/dallin/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt ', 'send_anonymous_usage_stats': 'True'}
[0m16:51:16.063228 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt_project.yml does not parse to a dictionary
[0m16:51:16.064688 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.050356373, "process_in_blocks": "0", "process_kernel_time": 0.096193, "process_mem_max_rss": "108462080", "process_out_blocks": "0", "process_user_time": 0.712887}
[0m16:51:16.065111 [debug] [MainThread]: Command `cli deps` failed at 16:51:16.065048 after 0.05 seconds
[0m16:51:16.065346 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112241640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112e07f20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11315bcb0>]}
[0m16:51:16.065563 [debug] [MainThread]: An error was encountered while trying to send an event
[0m16:51:16.065718 [debug] [MainThread]: Flushing usage events
